version: "3"
services:
    cassandra:
        image: cassandra
        container_name: cassandra
        ports: 
            - "9042"
        restart: always
        hostname: cassandra
        volumes: 
            - ./cassandradb/:/var/lib/cassandra
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181"
        restart: always
        hostname: zookeeper
        depends_on:
            - cassandra
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://127.0.0.1:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        depends_on:
            - zookeeper
        restart: always
    account:
        image: account
        container_name: account
        ports:
            - "8085"
        restart: always
        hostname: account
        volumes: 
            - ./neoflex/bankAccount/src/main/resources/static/files/:/src/main/resources/static/files/
        environment: 
            - path.files.resources=/src/main/resources/static/files/
    keyspace:
        image: keyspace
        container_name: keyspace
        ports: 
            - "8080"
        depends_on: 
            - cassandra
    producer:
        image: producer
        container_name: producer
        ports:
            - "8081"
        restart: always
        depends_on:
            - kafka
        environment: 
            - kafka.bootstrap-servers=kafka:9093,127.0.0.1:9092
            - kafka.topic.name=bankaccount
            - producer.service.url=http://account:8085
    address:
        image: address
        container_name: address
        ports:
            - "8090"
        restart: always
        hostname: address
        environment: 
            - address.generate.url=https://randomapi.com/api/6fa35931fb2d9879e3e4daa640d8d9e5?fmt=prettyraw&sole
            - kafka.bootstrap.servers=kafka:9093,localhost:9092
            - kafka.topic.for.read=bankaccount
            - kafka.topic.for.write=address
            - kafka.appName=address
        depends_on:
            - kafka
    request:
        image: request
        container_name: request
        ports:
            - "8088:8088"
        restart: always
        hostname: request
        depends_on:
            - cassandra
            - keyspace
        environment: 
            - spring.data.cassandra.keyspace-name=bankaccount_keyspace
            - spring.data.cassandra.contact-points=cassandra
            - spring.data.cassandra.port=9042
            - spring.data.cassandra.local-datacenter=datacenter1
            - spring.data.cassandra.read-timeout-millis=15000
    grpc_server:
        image: grpc_server
        container_name: grpcserver
        ports:
            - "8084"
        restart: always
        depends_on:
            - cassandra
        environment: 
            - grpc.server.port=8084
            - spring.data.cassandra.keyspace-name=bankaccount_keyspace
            - spring.data.cassandra.contact-points=cassandra
            - spring.data.cassandra.port=9042
            - spring.data.cassandra.local-datacenter=datacenter1
            - spring.data.cassandra.read-timeout-millis=15000
    grpc_client:
        image: grpc_client
        container_name: grpc_client
        ports:
            - "8086:8086"
        restart: always
        depends_on:
            - grpc_server
        environment: 
            - grpc.hostname=grpcserver
            - grpc.port=8084
    rsocket_server:
        image: rsocket_server
        container_name: rsocket_server
        ports:
            - "7001"
        restart: always
        hostname: rsocket_server
        depends_on:
            - cassandra
        environment: 
            - spring.main.lazy-initialization=true
            - spring.rsocket.server.port=7001
            - spring.data.cassandra.keyspace-name=bankaccount_keyspace
            - spring.data.cassandra.contact-points=cassandra
            - spring.data.cassandra.port=9042
            - spring.data.cassandra.local-datacenter=datacenter1
            - spring.data.cassandra.read-timeout-millis=15000
    rsocket_client:
        image: rsocket_client
        container_name: rsocket_client
        ports:
            - "8087:8087"
        restart: always
        hostname: rsocket_client
        depends_on:
            - cassandra
            - rsocket_server
        environment: 
            - rsocket.server.hostname=rsocket_server
            - rsocket.server.port=7001